### ISSUE TITLE
In Stata 17,the command "streamplot new_cases date if date > 22400, by(region)" gets no result

### ISSUE THREAD

**Issue by zdlspace0528** [asjadnaqvi/The-Stata-Guide#1]
Dear @ [asjadnaqvi](https://github.com/asjadnaqvi)

I have run the example of `streamplot`,

`streamplot new_cases date if date > 22400, by(region)`

But there is no result,the default color is CET C6,So I modified the adofile,Now it works well.
```java
if "`palette'" == "" {
		local mycolor "CET C6"
	}
	else {
		local mycolor `palette'
	}
```

Here it should be "CET C6",not CET C6.There should be quotes here,or it gets no graph.

**Comment by asjadnaqvi** [comment]
Thank you for testing this! Patched on GitHub
